---
title: "read_data"
author: "Yang Yu"
date: "2021/12/2"
output: pdf_document
---

# Read DATA
```{r}
qsar_raw = read.csv2("data/biodeg.csv",header = FALSE);
names(qsar_raw) <- c('SpMax_L',
                     'J_Dz_e',
                     'nHM',
                     'F01_N_N',
                     'F04_C_N',
                     'NssssC',
                     'nCb',
                     'C',
                     'nCp',
                     'nO',
                     'F03_C_N',
                     'SdssC',
                     'HyWiB_m',
                     'LOC',
                     'SM6_L',
                     'F03C_O',
                     'Me',
                     'Mi',
                     'nN_N',
                     'nArNO2',
                     'nCRX3',
                     'SpPosA_B_p',
                     'nCIR',
                     'B01_C_Br',
                     'B03_C_Cl',
                     'N_073',
                     'SpMax_A',
                     'Psi_i_1d',
                     'B04_C_Br',
                     'SdO',
                     'TI2_L',
                     'nCrt',
                     'C_026',
                     'F02_C_N',
                     'nHDon',
                     'SpMax_B_m',
                     'Psi_i_A',
                     'nN',
                     'SM6_B_m',
                     'nArCOOR',
                     'nX',
                     'class');
qsar_raw$SpMax_L<-as.numeric(qsar_raw$SpMax_L)
qsar_raw$J_Dz_e<-as.numeric(qsar_raw$J_Dz_e)
qsar_raw$C<-as.numeric(qsar_raw$C)
qsar_raw$SdssC<-as.numeric(qsar_raw$SdssC)
qsar_raw$HyWiB_m<-as.numeric(qsar_raw$HyWiB_m)
qsar_raw$LOC<-as.numeric(qsar_raw$LOC)
qsar_raw$SM6_L<-as.numeric(qsar_raw$SM6_L)
qsar_raw$Me<-as.numeric(qsar_raw$Me)
qsar_raw$Mi<-as.numeric(qsar_raw$Mi)
qsar_raw$SpPosA_B_p<-as.numeric(qsar_raw$SpPosA_B_p)
qsar_raw$SpMax_A<-as.numeric(qsar_raw$SpMax_A)
qsar_raw$Psi_i_1d<-as.numeric(qsar_raw$Psi_i_1d)
qsar_raw$SdO<-as.numeric(qsar_raw$SdO)
qsar_raw$TI2_L<-as.numeric(qsar_raw$TI2_L)
qsar_raw$SpMax_B_m<-as.numeric(qsar_raw$SpMax_B_m)
qsar_raw$Psi_i_A<-as.numeric(qsar_raw$Psi_i_A)
qsar_raw$SM6_B_m<-as.numeric(qsar_raw$SM6_B_m)
for (i in 1:1055) {
  if (qsar_raw$class[i] == "RB") {
    qsar_raw$class[i]<-"0"
  }
  else {
    qsar_raw$class[i]<-"1"
  }
}
qsar_raw$class<-as.integer(qsar_raw$class)
#test_index<-sample(1055, 128)
qsar_train<-qsar_raw[(1:837), ]
qsar_test<-qsar_raw[-(1:837), ]

qsar_raw
```


# Implement the following method: 
# 1.LDA 2.Naive bayes 3. Decision Tree 4. Bagging 5. RandomForest


# 1. LDA
```{r}
# attach(qsar_raw)
library(MASS)
# create lda model
lda.fit <- lda(class ~ ., data = qsar_train)
# lda.fit


# predict
lda.pred <- predict(lda.fit, qsar_test)
# names(lda.predict)
# lda.predict
lda.class <- lda.pred$class
# lda.class


# make table and compute test error
table(lda.class, qsar_test$class)
mean(lda.class == qsar_test$class)


```



# 2. naive bayes
```{r}
library(e1071)

# create model
nb.fit <- naiveBayes(class ~.,data = qsar_train)
# nb.fit


# PREDICT
nb.class <- predict(nb.fit, qsar_test)
# nb.class

# TSET ERROR
table(nb.class, qsar_test$class)
mean(nb.class == qsar_test$class)

```

```{r}
cor.qsar <- cor(qsar_raw)
library(corrplot)
corrplot(cor.qsar, method="color",tl.col="black", tl.cex = 0.5)

```


# 3.1 decision tree without pruning
```{r}
library(tree)

# create model 
tree.qsar <- tree(as.factor(class) ~.,data = qsar_train)
summary(tree.qsar)


#plot
# plot(tree.qsar)
# # text(tree.qsar, pretty = 0,type = c("proportional", "uniform"))
# text(tree.qsar, pretty = 0)

# rpart.plot(tree.qsar, box.palette="RdBu", shadow.col="gray", nn=TRUE)

# predict
tree.pred <- predict(tree.qsar, qsar_test, type = "class") 
# tree.pred

#test error
table(tree.pred, qsar_test$class)
mean(tree.pred == qsar_test$class)
```

# 3.2 decision tree with pruning
```{r}

# add panalty a|T|
set.seed(3)
cv.qsar <- cv.tree(tree.qsar,FUN = prune.misclass) 
cv.qsar
plot(cv.qsar$size, cv.qsar$dev, type = "b", xlab = "Tree Size", ylab = "Deviance")


# size = 15 is the optimal tree


# get model
prune.tree.qsar <- prune.misclass(tree.qsar, best = 12)
plot(prune.tree.qsar)
text(prune.tree.qsar, pretty = 0)


# predict
tree.pred.prun<- predict(prune.tree.qsar, qsar_test, type = "class")

# test error
table(tree.pred.prun, qsar_test$class)
mean(tree.pred.prun == qsar_test$class)

## the pruning tree is optimal

```


# 4. bagging

```{r}
library(randomForest)
# rfNews()


# CREATE MODEL
set.seed(1)
bag.qsar <- randomForest(as.factor(class) ~.,data = qsar_train, mtry = 41, importance = TRUE)
# bag.qsar


# PREDICT
bag.pred <- predict(bag.qsar, newdata = qsar_test)
# bag.pred


# TEST ERROR
table(bag.pred, qsar_test$class)
mean(bag.pred == qsar_test$class)

```


# 5. randomForest

```{r}
# CREATE MODEL
set.seed(1)
forest.qsar <- randomForest(as.factor(class) ~.,data = qsar_train, importance = TRUE)
# forest.qsar


# PREDICT
forest.pred <- predict(forest.qsar, newdata = qsar_test)
# forest.pred


# TEST ERROR
table(forest.pred, qsar_test$class)
mean(forest.pred == qsar_test$class)
```




# Now draw some pics!!!!


# DRAW CONFUSION MATRIX: 1. EMPTY TABLE
```{r}
library(dplyr)
library(tidyr)
library(caret)
library(ggplot2)
library(reshape2)
pred = factor(lda.class)
levels(pred)
truth = factor(qsar_test$class)
levels(truth)
confusionMatrix(pred, truth)
input.mat = as.matrix(confusionMatrix(pred, truth))
normalized.mat = sweep(input.mat, 2, colSums(input.mat), "/" )
melt.mat <- melt(normalized.mat)
ggplot(data = melt.mat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + ggtitle("Confusion Matrix of  linear regression for conventional features") +
  xlab("Prediction") + ylab("truth") + labs(fill = "frequency")
```


# DRAW CONFUSION MATRIX: 2. fourfoldplot
```{r}
library(caret)
library(ggplot2)
cm.lda <- confusionMatrix(as.factor(lda.class), as.factor(qsar_test$class))
fourfoldplot(cm.lda$table, main = "Confusion Matrix of LDA", std="ind.max")


# cm.nb <- confusionMatrix(as.factor(nb.class), as.factor(qsar_test$class))
# fourfoldplot(cm.nb$table, main = "Confusion Matrix of Naive Bayes")
# 
# cm.tree <- confusionMatrix(as.factor(tree.pred), as.factor(qsar_test$class))
# fourfoldplot(cm.tree$table, main = "Confusion Matrix of Decision Tree")

```


# DRAW CONFUSION MATRIX: 3. TABLE WITH STATISTICS

```{r}
draw_confusion_matrix <- function(cm) {

  layout(matrix(c(1,1,2)))
  par(mar=c(2,2,2,2))
  plot(c(100, 345), c(300, 450), type = "n", xlab="", ylab="", xaxt='n', yaxt='n')
  title('CONFUSION MATRIX', cex.main=2)

  # create the matrix 
  rect(150, 430, 240, 370, col='#3F97D0')
  text(195, 435, 'RB', cex=1.2)
  rect(250, 430, 340, 370, col='#F7AD50')
  text(295, 435, 'NRB', cex=1.2)
  text(125, 370, 'Predicted', cex=1.3, srt=90, font=2)
  text(245, 450, 'Actual', cex=1.3, font=2)
  rect(150, 305, 240, 365, col='#F7AD50')
  rect(250, 305, 340, 365, col='#3F97D0')
  text(140, 400, 'RB', cex=1.2, srt=90)
  text(140, 335, 'NRB', cex=1.2, srt=90)

  # add in the cm results 
  res <- as.numeric(cm$table)
  text(195, 400, res[1], cex=1.6, font=2, col='white')
  text(195, 335, res[2], cex=1.6, font=2, col='white')
  text(295, 400, res[3], cex=1.6, font=2, col='white')
  text(295, 335, res[4], cex=1.6, font=2, col='white')

  # add in the specifics 
  plot(c(100, 0), c(100, 0), type = "n", xlab="", ylab="", main = "DETAILS", xaxt='n', yaxt='n')
  text(10, 85, names(cm$byClass[1]), cex=1.2, font=2)
  text(10, 70, round(as.numeric(cm$byClass[1]), 3), cex=1.2)
  text(30, 85, names(cm$byClass[2]), cex=1.2, font=2)
  text(30, 70, round(as.numeric(cm$byClass[2]), 3), cex=1.2)
  text(50, 85, names(cm$byClass[5]), cex=1.2, font=2)
  text(50, 70, round(as.numeric(cm$byClass[5]), 3), cex=1.2)
  text(70, 85, names(cm$byClass[6]), cex=1.2, font=2)
  text(70, 70, round(as.numeric(cm$byClass[6]), 3), cex=1.2)
  text(90, 85, names(cm$byClass[7]), cex=1.2, font=2)
  text(90, 70, round(as.numeric(cm$byClass[7]), 3), cex=1.2)

  # add in the accuracy information 
  text(30, 35, names(cm$overall[1]), cex=1.5, font=2)
  text(30, 20, round(as.numeric(cm$overall[1]), 3), cex=1.4)
  text(70, 35, names(cm$overall[2]), cex=1.5, font=2)
  text(70, 20, round(as.numeric(cm$overall[2]), 3), cex=1.4)
} 

```


```{r}
library(caret)


cm.lda <- confusionMatrix(as.factor(lda.class), as.factor(qsar_test$class))
draw_confusion_matrix(cm.lda)

cm.nb <- confusionMatrix(as.factor(nb.class), as.factor(qsar_test$class))
draw_confusion_matrix(cm.nb)

cm.tree <- confusionMatrix(as.factor(tree.pred), as.factor(qsar_test$class))
draw_confusion_matrix(cm.tree)

cm.tree.prun <- confusionMatrix(as.factor(tree.pred.prun), as.factor(qsar_test$class))
draw_confusion_matrix(cm.tree.prun)

cm.bag <- confusionMatrix(as.factor(bag.pred), as.factor(qsar_test$class))
draw_confusion_matrix(cm.bag)

cm.forest <- confusionMatrix(as.factor(forest.pred), as.factor(qsar_test$class))
draw_confusion_matrix(cm.forest)

```

